# Generated by Django 5.1 on 2024-09-08 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignUp_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("UserId", models.CharField(max_length=150, unique=True)),
                ("UserPassword", models.CharField(max_length=150)),
                ("UserName", models.CharField(max_length=100)),
                ("UserEmail", models.EmailField(max_length=200, unique=True)),
                ("UserPhone", models.CharField(max_length=15)),
                ("UserAddress", models.CharField(max_length=250)),
                ("UserAddress_detail", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("modelNamev", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "maintenance",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantity", models.IntegerField()),
                ("size", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("power", models.FloatField()),
                ("record", models.DateField(blank=True, null=True)),
                ("cause", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
